#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const js = fs.readFileSync(path.resolve(__dirname, '../app/src/main/assets/cheatsheet.js'), 'utf8');
const css = fs.readFileSync(path.resolve(__dirname, '../app/src/main/assets/cheatsheet.css'), 'utf8');
const activity = fs.readFileSync(path.resolve(__dirname, '../app/src/main/java/org/apollo/agcdsky/MainActivity.java'), 'utf8');
const sensorActivity = fs.readFileSync(path.resolve(__dirname, '../app/src/main/java/org/apollo/agcdsky/SensorMainActivity.java'), 'utf8');
const apple = fs.readFileSync(path.resolve(__dirname, '../apple/Sources/AGCWebView.swift'), 'utf8');
const style = fs.readFileSync(path.resolve(__dirname, '../app/src/main/assets/style.css'), 'utf8');
function assert(ok, msg) { if (!ok) throw new Error(msg); }
const headStart = js.indexOf('<div class="cheat-head" id="cheat-drag">');
const tabsStart = js.indexOf('<div class="cheat-tabs">');
const actionsStart = js.indexOf('<div class="cheat-head-actions">');
const actionsClose = js.indexOf('</div>', actionsStart);
assert(headStart >= 0 && actionsStart > headStart, 'cheat sheet header/action markup missing');
assert(tabsStart > actionsClose, 'cheat tabs must not live inside the draggable header');
assert(js.includes("sheet.classList.contains('open')?close():open()"), 'CHEAT launcher must toggle sheet closed/open');
assert(js.includes("sheet.classList.remove('open','minimized')"), 'close must fully dismiss/reset sheet');
assert(css.includes('.cheat-head-actions{display:flex'), 'fixed header action container missing');
assert(css.includes('#cheat-print,#cheat-min,#cheat-close{\n  min-width:44px;\n  min-height:36px'), 'print/close/minimize touch targets too small');
assert(css.includes('overflow-x:auto'), 'tabs must scroll instead of pushing close control off-screen');
assert(js.includes('id="cheat-print"'), 'print button missing from checklist header');
assert(js.includes("PrintBridge.printChecklist()"), 'checklist print button must invoke native print bridge');
assert(css.includes('size:Letter landscape'), 'model checklist must print on US Letter landscape');
assert(js.includes('data-cheat-pane="p51real-cont"'), 'print-only P51 REAL SKY continuation page missing');
assert(js.includes("'cheat-print-continuation'"), 'long P51 REAL SKY rows must be moved to the continuation card for print');
assert(css.includes('grid-template-columns:repeat(3,3.40in)!important'), 'model checklist must impose three portrait cards across Letter landscape');
assert(css.includes('grid-auto-rows:7.65in!important'), 'model checklist cards must use equal tall page heights');
assert(css.includes('.cheat-pane[data-cheat-pane="quick"]{'), 'second physical sheet must begin at checklist page 4');
assert(css.includes('column-gap:.12in!important'), 'model checklist must reserve narrow cutting gutters');
assert(css.includes('width:3.40in!important') && css.includes('height:7.65in!important'), 'model checklist page dimensions missing');
assert(css.includes('PAGE 1 / 6 · CUT ON DASHED GUIDE') && css.includes('PAGE 6 / 6 · CUT ON DASHED GUIDE'), 'model checklist must print six page-numbered cut footers');
assert(css.includes('outline:.4pt dashed #888!important'), 'model checklist must include visible cut guides');
assert(!css.includes('grid-template-columns:repeat(2,5.10in)!important'), 'obsolete four-up card layout returned');
assert(!css.includes('grid-auto-rows:3.80in!important'), 'obsolete clipped 3.80-inch card height returned');
assert(activity.includes('PrintAttributes.MediaSize.NA_LETTER.asLandscape()'), 'legacy Android checklist must request Letter landscape media');
assert(activity.includes('addJavascriptInterface(new ChecklistPrintBridge(),"PrintBridge")'), 'PrintBridge must be installed on the WebView');
assert(activity.includes('WebViewTeardown.destroy(doomed,"DebugBridge","TimeBridge","PrintBridge")'), 'legacy activity PrintBridge/TimeBridge must be removed during WebView teardown');
assert(sensorActivity.includes('addJavascriptInterface(new ChecklistPrintBridge(),"PrintBridge")'), 'real Android launcher must install PrintBridge');
assert(sensorActivity.includes('PrintAttributes.MediaSize.NA_LETTER.asLandscape()'), 'real Android launcher checklist must request Letter landscape media');
assert(sensorActivity.includes('WebViewTeardown.destroy(doomed,"DebugBridge","SkyBridge","TimeBridge","PrintBridge")'), 'real Android launcher must remove PrintBridge during teardown');
assert(apple.includes('configuration.userContentController.add(self, name: "PrintBridge")'), 'Apple PrintBridge must be installed');
assert(apple.includes('window.webkit.messageHandlers.PrintBridge.postMessage'), 'Apple PrintBridge JavaScript shim missing');
assert(apple.includes('width: 11.0 * 72.0, height: 8.5 * 72.0'), 'iOS checklist print renderer must be US Letter landscape');
assert(apple.includes('printInfo.paperSize = NSSize(width: 8.5 * 72.0, height: 11.0 * 72.0)'), 'macOS must use standard US Letter stock');
assert((apple.match(/orientation = \.landscape/g)||[]).length >= 2, 'iOS and macOS checklist printing must both request landscape orientation');
assert(apple.includes('printInfo.topMargin = 0') && apple.includes('printInfo.rightMargin = 0'), 'Apple native print margins must defer to shared Letter CSS');
assert(apple.includes('removeScriptMessageHandler(forName: "PrintBridge")'), 'Apple PrintBridge must be removed during teardown');
assert(!style.includes('.el-seg.off'), 'legacy unlit numeric EL styling must not return');
assert(style.includes('.el-seg{\n  display:none;\n  fill:none;\n  stroke:none;\n  opacity:0;'), 'de-energized numeric/sign EL paths must be optically absent');
assert(style.includes('.el-seg.on{\n  display:inline;\n  fill:var(--el);'), 'energized numeric/sign EL paths must explicitly opt into visibility');
assert(!style.includes('.comp-el:not(.on){display:none}'), 'COMP ACTY printed legend must remain visible while de-energized');
assert(style.includes('.el-comp-bg{\n  display:none;\n  fill:none;\n  stroke:none;\n  opacity:0;'), 'de-energized COMP ACTY phosphor must be optically absent');
assert(style.includes('.comp-el.on .el-comp-bg{\n  display:block;\n  fill:var(--el);'), 'COMP ACTY phosphor must appear only when energized');
console.log('cheat sheet smoke: PASS');
